### ISSUE TITLE
Java 17 Pre-requisite necessity

### ISSUE THREAD

**Issue by azriel-healthpoint** [tewhatuora/nems-subscriber-java#2]
Hi there, the project mentions Java 17 as a pre-requisite, is it a technical requirement, or "makes development life easier"? (because I know it does)

I briefly scanned the code, and it doesn't appear Java 17 features are used. Does the requirement come from the dependencies?

Also, if it's simply "we want to support Java 17 without needing to maintain support for earlier versions of Java", that's cool too.

**Comment by jdttaylor** [comment]
Any java version that is supported in the following link will work https://www.oracle.com/java/technologies/java-se-support-roadmap.html. However Java 17 was chosen as it is the latest LTS -1 version.

It should also be noted that Java 17 was the version used to build the code.

**Comment by azriel-healthpoint** [comment]
Cool thanks; I guess the key part is what the Solace client [supports](https://docs.solace.com/API/API-Developer-Guide-Java/Java-API-supported-environments.htm), and they follow the supported Java versions.
